# Generated by Django 4.2.1 on 2023-05-21 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('data', models.CharField(max_length=250, verbose_name='data')),
                ('time', models.CharField(max_length=250, verbose_name='time')),
                ('type', models.CharField(max_length=250, verbose_name='type')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('address', models.CharField(max_length=250, verbose_name='address')),
                ('coordinates', models.CharField(default=0, max_length=250, verbose_name='coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('data', models.CharField(max_length=250, verbose_name='data')),
                ('time', models.CharField(max_length=250, verbose_name='time')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('id_decision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.decision', verbose_name='id решения')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('type', models.CharField(max_length=250, verbose_name='type')),
                ('maker', models.CharField(max_length=250, verbose_name='maker')),
                ('data', models.CharField(max_length=250, verbose_name='data')),
                ('voltage', models.CharField(max_length=250, verbose_name='Напряжение в сети (вольты)')),
                ('current', models.CharField(max_length=250, verbose_name='Ток потребления (амперы)')),
                ('power', models.CharField(max_length=250, verbose_name='Мощность потребления (ватты)')),
                ('power_factor', models.CharField(max_length=250, verbose_name='Коэффициент мощности (безразмерный параметр)')),
                ('frequency', models.CharField(max_length=250, verbose_name='Частота тока (герцы)')),
                ('noise', models.CharField(max_length=250, verbose_name='Уровень шума и помех в сети (дБ)')),
                ('duration', models.CharField(max_length=250, verbose_name='Длительность перерывов в электроснабжении (минуты)')),
                ('phase_angle', models.CharField(max_length=250, verbose_name='Фазный угол (градусы)')),
                ('resistance', models.CharField(max_length=250, verbose_name='Сопротивление проводов и кабелей (омы)')),
                ('temperature', models.CharField(max_length=250, verbose_name='Температура окружающей среды и оборудования (градусы Цельсия)')),
                ('id_station', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.station', verbose_name='id станции')),
            ],
        ),
    ]
