# Generated by Django 4.2.1 on 2023-05-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='device',
            name='phase_angle',
        ),
        migrations.RemoveField(
            model_name='device',
            name='power',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='time',
        ),
        migrations.AddField(
            model_name='decision',
            name='id_station',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.station', verbose_name='id станции'),
        ),
        migrations.AddField(
            model_name='device',
            name='current_phase_angle',
            field=models.FloatField(default=0, max_length=250, verbose_name='Фазный угол тока (градусы)'),
        ),
        migrations.AddField(
            model_name='device',
            name='voltage_phase_angle',
            field=models.FloatField(default=0, max_length=250, verbose_name='Фазный угол напряжения (градусы)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='current',
            field=models.FloatField(max_length=250, verbose_name='Ток потребления (амперы)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='frequency',
            field=models.FloatField(max_length=250, verbose_name='Частота тока (герцы)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='noise',
            field=models.FloatField(max_length=250, verbose_name='Уровень шума и помех в сети (дБ)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='power_factor',
            field=models.FloatField(max_length=250, verbose_name='Коэффициент мощности (безразмерный параметр)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='resistance',
            field=models.FloatField(max_length=250, verbose_name='Сопротивление проводов и кабелей (омы)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.FloatField(max_length=250, verbose_name='Температура окружающей среды и оборудования (градусы Цельсия)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='voltage',
            field=models.FloatField(max_length=250, verbose_name='Напряжение в сети (вольты)'),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('data', models.CharField(max_length=250, verbose_name='data')),
                ('value', models.FloatField(max_length=250, verbose_name='value')),
                ('id_device', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.device', verbose_name='id прибора')),
            ],
        ),
    ]
