# Generated by Django 4.2.1 on 2023-05-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_device_interference_alter_device_noise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Values',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.device')),
            ],
            bases=('main.device',),
        ),
    ]
